version: "3.8"

configs:
  proxy_config:
    content: |
      providers:
        web3-rpc-provider:
          url: "http://web3-rpc-provider:3000/endpoints"
          sources:
          - ChainList

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: web3_rpc_proxy_db
    networks: [app-bridge]
    ports: [5432:5432]

  redis:
    image: redis:alpine
    ports: [6379:6379]
    networks: [app-bridge]

  # provides the free web3 rpc
  web3-rpc-provider:
    image: web3-rpc-provider:v1.0.0
    networks: [app-bridge]
    ports: [3000:3000]

  web3-rpc-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    configs:
      - source: proxy_config
        target: /app/default.yaml
        mode: 0440
    depends_on:
      - web3-rpc-provider
      - postgres
      - redis
    links:
      - web3-rpc-provider
      - postgres
      - redis
    networks: [app-bridge]
    ports: [8080:8080]

networks:
  app-bridge:
    driver: bridge
