name: web3app

configs:
  proxy_config:
    content: |
      providers:
        web3-rpc-provider:
          url: "http://provider:3000/endpoints"
          sources:
          - ChainList
      logger:
        level: info

services:
  # Enable when you need tenant isolation and rate limiting
  # postgres:
  #   image: postgres:16.4-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: "123456"
  #     POSTGRES_DB: web3_rpc_proxy_db
  #   networks: [app-bridge]
  #   ports: [5432:5432]

  # Enable when you need tenant isolation and rate limiting
  # redis:
  #   image: redis:7.4.0-alpine
  #   ports: [6379:6379]
  #   networks: [app-bridge]

  # Provides the free web3 rpc
  provider:
    image: dodozoo/we3-rpc-provider:v1.0.0
    networks: [app-bridge]
    ports: [3000:3000]

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    configs:
      - source: proxy_config
        target: /app/config/default.yaml
        mode: 0666
    depends_on:
      - provider
      # - postgres
      # - redis
    links:
      - provider
      # - postgres
      # - redis
    networks: [app-bridge]
    ports: [8080:8080]

networks:
  app-bridge:
    driver: bridge
