// Code generated by MockGen. DO NOT EDIT.
// Source: internal/module/agent/service/agent_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/module/agent/service/agent_service.go -destination=internal/module/agent/service/agent_service_mock.go -package=service
//

// Package service is a generated GoMock package.
package service



// func TestCall(t *testing.T)  {
// 	ctrl := gomock.NewController(t)
// 	defer ctrl.Finish()
// 	client := core.NewMockClient(ctrl)
// 	tenantService := NewMockTenantService(ctrl)
// 	// cfg := koanf.New(".")

// 	agentService := NewAgentService(
// 		nil,
// 		client,
// 		nil,
// 		zerolog.Nop(),
// 		tenantService,
// 	)

// 	ctx := &fasthttp.RequestCtx{
// 		Request: fasthttp.Request{
// 			Header:        fasthttp.RequestHeader{},
// 			UseHostHeader: false,
// 		},
// 		Response: fasthttp.Response{},
// 	}
// 	ctx.Request.Header.SetMethod("GET")
// 	ctx.Request.Header.Set("x", "test")
// 	ctx.Request.Header.Set("y", "test")
// 	ctx.Request.SetRequestURI("/1")
// 	ctx.Request.SetHost("test")
// 	// ctx.Response.Header.Set("Location", "test")
// 	// ctx.Response.SetStatusCode(200)


// 	// 正常
// 	agentService.Call(ctx)
// 	// 异常
// 	// 超时
// 	// 拒绝
// 	// 拦截
// }