# default.yaml is the default configuration file
# For local development, you can create a local.yaml to override the default configuration

# Service configuration
app:
  # Service name
  name: "Web3 RPC Proxy"
  # Host and port where the service listens
  host: :8080
  # Expiration time for keep-alive connections
  idle-timeout: 30s
  # Print registered routes
  print-routes: false
  # Whether to enable prefork
  prefork: false
  # Enable production mode
  production: false

# Logger configuration
logger:
  level: info

# Database configuration
# database:
#   postgres:
#     dsn: 'postgres://your-postgres-host:5432/your_db_name'

# Redis configuration for data caching
# redis:
#   url: 'redis://your-redis-host:6379'

# AMQP configuration, after startup, the service will automatically create an exchange
# based on the following configuration and send request information to this exchange
# amqp:
#   url: amqp://your-mq-host:5672
#   exchange: "your-exchange-name" # default: "web3rpcproxy.query.topic"
#   exchange-type: "topic"

# Tenant configuration
# tenant:
#   enable: true # Enable tenants rate limit

# Data caching
evm:
  cache_results_duration: &evm_cache_results_duration
    net_version: 1h
    eth_chainId: 1h
    eth_getTransactionCount: 5m
    eth_getBlockTransactionCountByNumber: 5m
    eth_getBlockTransactionCountByHash: 5m
    eth_getUncleCountByBlockHash: 5m
    eth_getUncleCountByBlockNumber: 5m
    eth_blockNumber: 0.1s
    eth_getBlockByNumber: 10m
    eth_getBlockByHash: 10m
    eth_getTransactionByHash: 10m
    eth_getTransactionByBlockHashAndIndex: 10m
    eth_getTransactionByBlockNumberAndIndex: 10m
    eth_getTransactionReceipt: 10m
    eth_getLogs: 1m
    eth_getUncleByBlockHashAndIndex: 10m
    eth_getUncleByBlockNumberAndIndex: 10m

svm:
  cache_results_duration: 
    getSlotLeaders: 1m
    getBlocks: 1m
    getMultipleAccounts: 1m
    getHealth: 1m
    getSupply: 1m
  
    getBalance: 5m
    getBlockCommitment: 5m
    getAccountInfo: 5m
    getTokenAccountBalance: 5m
    getTokenAccountsByOwner: 5m
    getTokenAccountsByMint: 5m
    getSignaturesForAddress: 5m
    getFeeCalculatorForBlockhash: 5m
    getRecentPerformanceSamples: 5m
    getSlotLeader: 5m
    getTransactionCount: 5m
    getProgramAccounts: 5m
    getInflationReward: 5m
    getVoteAccounts: 5m
    getTokenLargestAccounts: 5m
    getBlockHeight: 5m
    getFeeForMessage: 5m
    getRecentPrioritizationFees: 5m
    getSignatureStatuses: 5m
    getTokenAccountsByDelegate: 5m

    getBlock: 10m
    getTransaction: 10m
    getBlockProduction: 10m
    getBlockTime: 10m
    getBlocksWithLimit: 10m
    getEpochInfo: 10m
    getFirstAvailableBlock: 10m
    getClusterNodes: 10m
    getInflationGovernor: 10m
    getInflationRate: 10m
    getLedgerSize: 10m
    getMinimumBalanceForRentExemption: 10m
    getGenesisHash: 10m
    getTokenSupply: 10m
    getEpochSchedule: 10m
    getAccountRentExemption: 10m
    getTokenAccountsByOwnerWithLimit: 10m
    getHighestSnapshotSlot: 10m
    getIdentity: 10m
    getLeaderSchedule: 10m
    getMaxRetransmitSlot: 10m
    getMaxShredInsertSlot: 10m
    getStakeMinimumDelegation: 10m
    minimumLedgerSlot: 10m

    getVersion: 1h
cache:
  results:
    # ! Deprecate on next version
    expiry_durations: *evm_cache_results_duration

# Provider configuration, it will auto load external endpoints
# providers:
#   web3-rpc-provider:
#     url: "http://your_host:3000/endpoints"
#     sources:
#     - ChainList

# Endpoint configuration, provides endpoint lists for each chain for the system to choose from
endpoints:
  # Chain ID
  - id: 1
    # Chain code
    code: eth
    # Different types of endpoints
    services:
      fullnode:
        list:
          - url: "https://eth-mainnet.g.alchemy.com/v2/xxxx-xxxx-xxxx-xxxx"
      activenode:
        list:
          - url: "https://api.mycryptoapi.com/eth"
          - url: "https://rpc.flashbots.net/"
          - url: "https://ethereumnodelight.app.runonflux.io"
          - url: "https://nodes.mewapi.io/rpc/eth"
  - id: 11155111
    code: sepolia
    # Provide a list of available endpoints for Sepolia, choose the best one from the provided list
    list:
      - url: "https://rpc.sepolia.org"
      - url: "https://rpc2.sepolia.org"
      - url: "https://rpc-sepolia.rockx.com"
      - url: "https://rpc.sepolia.ethpandaops.io"
