{
 "title": "Web3 RPC Proxy",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "job",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{container!=''}, job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes{job=~\"$job\"}, pod)"
    }
   },
   {
    "name": "chain",
    "query": {
     "query": "label_values(luffy_total_requests{pod=~\"$pod\"}, chain)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(luffy_total_requests{pod=~\"$pod\", chain=~\"$chain\"}, app)"
    }
   },
   {
    "name": "url",
    "query": {
     "query": "label_values(luffy_total_endpoints{pod=~\"$pod\", chain=~\"$chain\"}, url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "流量走势图",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(luffy_total_requests[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "30m 流量预测图",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((\n  predict_linear(luffy_total_requests[1h], 1800) - luffy_total_requests\n) / 1800) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "异常数走势图",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(luffy_total_endpoints{status!=\"200\"}[1m])) by (status, url)",
     "legendFormat": "{{status}}❗️ {{url}}"
    }
   ]
  },
  {
   "title": "异常走势图",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(luffy_total_endpoints{status!=\"200\"}[1m])",
     "legendFormat": "{{status}}❗️ {{url}}"
    }
   ]
  },
  {
   "title": "30m 限流预测图",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  predict_linear(luffy_total_endpoints{status=\"429\"}[1h], 1800) - luffy_total_endpoints{status=\"429\"}\n) / 1800",
     "legendFormat": "{{status}}❗️ {{url}}"
    }
   ]
  },
  {
   "title": "耗时走势图",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  avg(rate(\n      luffy_request_durations_bucket[1m]\n    ))\n  by (\n    chain,\n    le\n  )\n)\n-\nhistogram_quantile(0.95,\n  avg(rate(\n      luffy_endpoint_durations_bucket[1m]\n    ))\n  by (\n    chain,\n    le\n  )\n)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "消息队列发布量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(luffy_total_amqp_messages{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", app=~\"$app\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "租户请求量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(luffy_total_requests{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", app=~\"$app\"}[1m])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "P98 请求耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98,\n  avg(rate(\n      luffy_request_durations_bucket{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", app=~\"$app\"}[1m]\n    ))\n  by (\n    chain,\n    le\n  )\n)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "P98 实际耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.98,\n  avg(rate(\n      luffy_request_durations_bucket{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\"}[1m]\n    ))\n  by (\n    chain,\n    le\n  )\n)\n-\nhistogram_quantile(0.98,\n  avg(rate(\n      luffy_endpoint_durations_bucket{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\"}[1m]\n    ))\n  by (\n    chain,\n    le\n  )\n)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "请求状态",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(luffy_total_requests{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", app=~\"$app\"}[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "各链请求量占比图",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(luffy_total_requests{job=~\"$job\", pod=~\"$pod\", app=~\"$app\"}) by (chain)",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "请求状态占比图",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(luffy_total_requests{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", app=~\"$app\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Engress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "端点调用量",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(luffy_total_endpoints{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", url=~\"$url\"}[1m])) by (chain, url)",
       "legendFormat": "{{chain}} {{url}}"
      }
     ]
    },
    {
     "title": "P98 调用耗时",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.98,\n  avg(rate(\n      luffy_endpoint_durations_bucket{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", url=~\"$url\"}[1m]\n    ))\n  by (\n    chain,\n    url,\n    le\n  )\n)",
       "legendFormat": "{{chain}} {{url}}"
      }
     ]
    },
    {
     "title": "端点数",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(count(luffy_total_endpoints{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\"}) by (url))",
       "legendFormat": "endpoints"
      }
     ]
    },
    {
     "title": "调用状态",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(luffy_total_endpoints{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", url=~\"$url\"}[1m])) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "方法缓存数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(luffy_total_caches{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", app=~\"$app\", status=\"hit\"}[1m])) by (method)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "调用状态占比图",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(luffy_total_endpoints{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", url=~\"$url\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "缓存状态占比图",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(luffy_total_caches{job=~\"$job\", pod=~\"$pod\", chain=~\"$chain\", app=~\"$app\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=~\"$job\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=~\"$job\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\", pod=~\"$pod\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{job=~\"$job\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{job=~\"$job\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{job=~\"$job\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=~\"$job\", pod=~\"$pod\"}[$interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  }
 ]
}